### PR TITLE
Optimized ES6 code

### PR DESCRIPTION
**Pull request by mindflowgo**
Just ES6 cleanup/optimizations. Same functionality. Nice project, thx!

### CODE REVIEW

**Comment by mindflowgo** [comment]
Also added 2 examples to example directory based on your examples on github.

**Comment by raaihank** [comment]
Thanks for your PR. Will get back ASAP.

**Comment by raaihank** [comment]
Hey. Why did you close this?

**Comment by mindflowgo** [comment]
Sorry because I stupidly then did a whole bunch of changes, renamed files, etc that I realized were still being added to the PR and thus totally changing your code.

Let me try to do head pull of the changes I did at first and try to re-sub to you.

**Comment by raaihank** [comment]
No problem. Thank you for your interest. I would be happy to collaborate together and make it more cool :)

**Pull request closed without merging**
