### PR TITLE
ES6 Optimizations

### PR DESCRIPTION
**Pull request by mindflowgo**
Functionality nearly all the same (except I allow spaces in tags), otherwise just ES6 cleanup (const instead of let), more logical bridge name, etc.

If you are interested in even more changes that you may want to integrate/consider, however I didn't include them as they may over-change how you envisaged this plugin, you can see my full rewrite at: 

https://github.com/mindflowgo/js-input-tags
npm:
https://www.npmjs.com/package/js-input-tags

### CODE REVIEW

**Comment by raaihank** [comment]
Thank you very much. I will take some time and update.

**Comment by mindflowgo** [comment]
No problem, thanks for the awesome project. The ONLY real addition I can think may be useful is to allow drag-drop to re-organize the tags, again ideally done with very little code addition, as I like the idea of keeping it small and streamline. Anything you'd like to see added, how did you use it?

**Comment by raaihank** [comment]
Thank you for the drag and drop idea. Please feel free to create a issue :)

Could you clarify your last question?

**Review by raaihank — APPROVED** [review]
Thank you very much @mindflowgo

**Comment by mindflowgo** [comment]
See my project code. I implemented drag and drop. Tell me if you need help adding it to your version. It actually works quite well. 
 Sent from Proton Mail for iOS 
On Tue, Dec 10, 2024 at 02:03, Raihan Kabir ***@***.***&gt; wrote:  Thank you for the drag and drop idea. Please feel free to create a issue :)
Could you clarify your last question?

**Pull request merged**
